name: Check project

on: [push]

jobs:
  check-job:
    runs-on: ubuntu-latest

    steps:
      - name: Setup project
        run: make setup

      - name: Starting test
        run: make test

      - name: Starting linter
        run: make lint
