name: Check project

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup project
        run: make setup
      - name: Run tests
        run: make test
      - name: Run linter
        run: make lint
      - name: Hello from Hexlet!
        uses: hexlet-components/hello-from-hexlet-action@release
